export const sampleHouseData = [
  {
    id: "1",
    projectName: "Integrated Ramicon",
    localityName: "Goregaon West",
    minQuotedPrice: "12096000",
    maxQuotedPrice: "16464000",
    bhkConfigs: "1, 2",
    developerName: "Integrated Spaces",
    cityName: "Mumbai",
    city_id: "1",
    latitude: "19.1833429",
    longitude: "73.0862101",
    projectId: "137035",
    minCompletionDate: "Dec'26",
    maxCompletionDate: "Dec'26",
    reraData: true,
    percentage: 0,
    couponAmount: 0,
    image:
      "https://d1yf71jefu0far.cloudfront.net/frontend/fit-in/projectimages/26f0498f798fab8c574b0bf8784dbd15/fit-in/391x217/project_11886_1723110963.png",
    about:
      "Escape the City Hustle at Integrated Ramicon: Luxury Apartments in Jogeshwari Tired of city noise? Crave a peaceful retreat after work? Discover Integrated Ramicon, your dream haven in the heart of Jogeshwari. These thoughtfully designed flats offer luxurious living spaces at incredibly reasonable prices, making royalty accessible to everyone.Here's why Integrated Ramicon is more than just an apartment:* Tranquil Luxury: Step into beautifully appointed apartments that provide a sanctuary from the city's hustle and bustle.\n* Prime Location: Enjoy unmatched connectivity with easy access to essential landmarks, hospitals, schools, shopping centers, parks, and entertainment hubs in Jogeshwari.\n* Community Living: Benefit from a vibrant community atmosphere while enjoying the privacy of your own luxurious space.",
  },
  {
    id: "2",
    projectName: "Sunbeam Heights",
    localityName: "Andheri West",
    minQuotedPrice: "14224000",
    maxQuotedPrice: "36400000",
    bhkConfigs: "1, 2, 3",
    latitude: "19.1833429",
    longitude: "73.0862101",
    developerName: "Sunbeam Developers",
    cityName: "Mumbai",
    city_id: "1",
    projectId: "137038",
    minCompletionDate: "Dec'27",
    maxCompletionDate: "Dec'27",
    reraData: true,
    percentage: 0,
    couponAmount: 0,
    unlockFlag: false,
    about:
      "Escape the City Hustle at Integrated Ramicon: Luxury Apartments in Jogeshwari Tired of city noise? Crave a peaceful retreat after work? Discover Integrated Ramicon, your dream haven in the heart of Jogeshwari. These thoughtfully designed flats offer luxurious living spaces at incredibly reasonable prices, making royalty accessible to everyone.Here's why Integrated Ramicon is more than just an apartment:* Tranquil Luxury: Step into beautifully appointed apartments that provide a sanctuary from the city's hustle and bustle.\n* Prime Location: Enjoy unmatched connectivity with easy access to essential landmarks, hospitals, schools, shopping centers, parks, and entertainment hubs in Jogeshwari.\n* Community Living: Benefit from a vibrant community atmosphere while enjoying the privacy of your own luxurious space.",
    image:
      "https://d1yf71jefu0far.cloudfront.net/frontend/fit-in/projectimages/0d6cc1c1dbda6e2edba972d30b4afc37/fit-in/391x217/project_16858_1723111645.jpg",
  },
  {
    id: "3",
    projectName: "Integrated Ramicon",
    localityName: "Goregaon West",
    minQuotedPrice: "12096000",
    maxQuotedPrice: "16464000",
    bhkConfigs: "1, 2",
    developerName: "Integrated Spaces",
    cityName: "Mumbai",
    city_id: "1",
    latitude: "19.1833429",
    longitude: "73.0862101",
    projectId: "137035",
    minCompletionDate: "Dec'26",
    maxCompletionDate: "Dec'26",
    reraData: true,
    percentage: 0,
    couponAmount: 0,
    image:
      "https://d1yf71jefu0far.cloudfront.net/frontend/fit-in/projectimages/26f0498f798fab8c574b0bf8784dbd15/fit-in/391x217/project_11886_1723110963.png",
    about:
      "Escape the City Hustle at Integrated Ramicon: Luxury Apartments in Jogeshwari Tired of city noise? Crave a peaceful retreat after work? Discover Integrated Ramicon, your dream haven in the heart of Jogeshwari. These thoughtfully designed flats offer luxurious living spaces at incredibly reasonable prices, making royalty accessible to everyone.Here's why Integrated Ramicon is more than just an apartment:\n* Tranquil Luxury: Step into beautifully appointed apartments that provide a sanctuary from the city's hustle and bustle.\n* Prime Location: Enjoy unmatched connectivity with easy access to essential landmarks, hospitals, schools, shopping centers, parks, and entertainment hubs in Jogeshwari.\n* Community Living: Benefit from a vibrant community atmosphere while enjoying the privacy of your own luxurious space.",
  },
  {
    id: "4",
    projectName: "Sunbeam Heights",
    localityName: "Andheri West",
    minQuotedPrice: "14224000",
    maxQuotedPrice: "36400000",
    bhkConfigs: "1, 2, 3",
    developerName: "Sunbeam Developers",
    cityName: "Mumbai",
    city_id: "1",
    projectId: "137038",
    latitude: "19.1833429",
    longitude: "73.0862101",
    minCompletionDate: "Dec'27",
    maxCompletionDate: "Dec'27",
    reraData: true,
    percentage: 0,
    couponAmount: 0,
    unlockFlag: false,
    about:
      "Escape the City Hustle at Integrated Ramicon: Luxury Apartments in Jogeshwari Tired of city noise? Crave a peaceful retreat after work? Discover Integrated Ramicon, your dream haven in the heart of Jogeshwari. These thoughtfully designed flats offer luxurious living spaces at incredibly reasonable prices, making royalty accessible to everyone.Here's why Integrated Ramicon is more than just an apartment:\n* Tranquil Luxury: Step into beautifully appointed apartments that provide a sanctuary from the city's hustle and bustle.\n* Prime Location: Enjoy unmatched connectivity with easy access to essential landmarks, hospitals, schools, shopping centers, parks, and entertainment hubs in Jogeshwari.\n* Community Living: Benefit from a vibrant community atmosphere while enjoying the privacy of your own luxurious space.",
    image:
      "https://d1yf71jefu0far.cloudfront.net/frontend/fit-in/projectimages/0d6cc1c1dbda6e2edba972d30b4afc37/fit-in/391x217/project_16858_1723111645.jpg",
  },
  {
    id: "5",
    projectName: "Integrated Ramicon",
    localityName: "Goregaon West",
    minQuotedPrice: "12096000",
    maxQuotedPrice: "16464000",
    bhkConfigs: "1, 2",
    developerName: "Integrated Spaces",
    cityName: "Mumbai",
    city_id: "1",
    projectId: "137035",
    latitude: "19.1833429",
    longitude: "73.0862101",
    minCompletionDate: "Dec'26",
    maxCompletionDate: "Dec'26",
    reraData: true,
    percentage: 0,
    couponAmount: 0,
    image:
      "https://d1yf71jefu0far.cloudfront.net/frontend/fit-in/projectimages/26f0498f798fab8c574b0bf8784dbd15/fit-in/391x217/project_11886_1723110963.png",
    about:
      "Escape the City Hustle at Integrated Ramicon: Luxury Apartments in Jogeshwari Tired of city noise? Crave a peaceful retreat after work? Discover Integrated Ramicon, your dream haven in the heart of Jogeshwari. These thoughtfully designed flats offer luxurious living spaces at incredibly reasonable prices, making royalty accessible to everyone.Here's why Integrated Ramicon is more than just an apartment:\n* Tranquil Luxury: Step into beautifully appointed apartments that provide a sanctuary from the city's hustle and bustle.\n* Prime Location: Enjoy unmatched connectivity with easy access to essential landmarks, hospitals, schools, shopping centers, parks, and entertainment hubs in Jogeshwari.\n* Community Living: Benefit from a vibrant community atmosphere while enjoying the privacy of your own luxurious space.",
  },
  {
    id: "6",
    projectName: "Sunbeam Heights",
    localityName: "Andheri West",
    minQuotedPrice: "14224000",
    maxQuotedPrice: "36400000",
    bhkConfigs: "1, 2, 3",
    developerName: "Sunbeam Developers",
    cityName: "Mumbai",
    city_id: "1",
    latitude: "19.1833429",
    longitude: "73.0862101",
    projectId: "137038",
    minCompletionDate: "Dec'27",
    maxCompletionDate: "Dec'27",
    reraData: true,
    percentage: 0,
    couponAmount: 0,
    unlockFlag: false,
    about:
      "Escape the City Hustle at Integrated Ramicon: Luxury Apartments in Jogeshwari Tired of city noise? Crave a peaceful retreat after work? Discover Integrated Ramicon, your dream haven in the heart of Jogeshwari. These thoughtfully designed flats offer luxurious living spaces at incredibly reasonable prices, making royalty accessible to everyone.Here's why Integrated Ramicon is more than just an apartment:\n* Tranquil Luxury: Step into beautifully appointed apartments that provide a sanctuary from the city's hustle and bustle.\n* Prime Location: Enjoy unmatched connectivity with easy access to essential landmarks, hospitals, schools, shopping centers, parks, and entertainment hubs in Jogeshwari.\n* Community Living: Benefit from a vibrant community atmosphere while enjoying the privacy of your own luxurious space.",
    image:
      "https://d1yf71jefu0far.cloudfront.net/frontend/fit-in/projectimages/0d6cc1c1dbda6e2edba972d30b4afc37/fit-in/391x217/project_16858_1723111645.jpg",
  },
];
